# Generated by Django 4.1.7 on 2023-07-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessuser',
            name='http_user_agent',
        ),
    ]
