# Generated by Django 4.1.7 on 2023-06-30 03:58

import core.erp.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de asistencia')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[('', '-----------'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=0)),
                ('day', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=64, unique=True)),
                ('firstname', models.CharField(max_length=64, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=64, verbose_name='Apellido')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Femenino')], default='male', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='Direcciones')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=core.erp.models.generate_employee_code, max_length=64, verbose_name='Codigo Empleado')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Salario')),
                ('estado', models.CharField(blank=True, choices=[('Contratado', 'Contratado'), ('Despedido', 'Despedido')], max_length=64, null=True, verbose_name='Estado')),
                ('hiring_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de contratación')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.departments', verbose_name='Departamento')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.candidatos', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='EmployeePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Descripcion')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.departments', verbose_name='Departamentos')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('start_turn', models.TimeField(default=datetime.time(0, 0), verbose_name='Inicio del turno')),
                ('end_turn', models.TimeField(default=datetime.time(0, 0), verbose_name='Fin del turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Referencia')),
                ('type', models.CharField(choices=[('remuneracion', 'REMUNERACION'), ('descuentos', 'DESCUENTOS')], default='Remuneraciones', max_length=15, verbose_name='Tipo')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('order', models.IntegerField(default=0, verbose_name='Posición')),
                ('has_quantity', models.BooleanField(default=False, verbose_name='¿Posee cantidad?')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(choices=[('', '-----------'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=0, verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(default=0.0)),
                ('expenses', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.employee', verbose_name='Empleado')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.salary')),
            ],
            options={
                'verbose_name': 'Salario Detalle',
                'verbose_name_plural': 'Salario Detalles',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Vacants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Mínimo salario')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Máximo salario')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employeepositions', verbose_name='Posiciones')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.candidatos', verbose_name='Candidatos')),
                ('vacants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.vacants', verbose_name='Vacantes')),
            ],
            options={
                'verbose_name': 'Seleccion',
                'verbose_name_plural': 'Selecciones',
            },
        ),
        migrations.CreateModel(
            name='SalaryHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('valor', models.FloatField(default=0.0)),
                ('headings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.headings')),
                ('salary_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.salarydetail')),
            ],
            options={
                'verbose_name': 'Detalle de Salario',
                'verbose_name_plural': 'Detalle de Salarios',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employeepositions', verbose_name='Posición'),
        ),
        migrations.AddField(
            model_name='employee',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employeeturn', verbose_name='Turno'),
        ),
        migrations.CreateModel(
            name='AssistanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.BooleanField(default=False)),
                ('assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.assistance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Detalle de Asistencia',
                'verbose_name_plural': 'Detalles de Asistencia',
                'default_permissions': (),
            },
        ),
    ]
