# Generated by Django 4.1.7 on 2023-04-06 01:56

import builtins
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64, verbose_name='País')),
                ('municipality', models.CharField(max_length=32, verbose_name='Municipio')),
                ('province', models.CharField(max_length=32, verbose_name='Provincia')),
                ('street', models.CharField(blank=True, max_length=64, null=True, verbose_name='Calle')),
                ('local_number', models.IntegerField(blank=True, null=True, verbose_name='Número de casa')),
                ('postal_code', models.IntegerField(blank=True, null=True, verbose_name='Código postal')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_turn', models.DateField(default=datetime.datetime(2023, 4, 5, 21, 56, 4, 176063), verbose_name='Incio del turno')),
                ('end_turn', models.DateField(default=datetime.datetime(2023, 4, 5, 21, 56, 4, 176063), verbose_name='Incio del turno')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=64, unique=True)),
                ('firstname', models.CharField(max_length=64, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=64, verbose_name='Apellido')),
                ('birthdate', models.DateField(default=datetime.date(2023, 4, 5), verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[(1, 'Masculino'), (2, 'Femenino')], default='Masculino', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Vacants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Mínimo salario')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Máximo salario')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.people', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salario')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.accounts', verbose_name='Cuenta de banco')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.departments', verbose_name='Departamento')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.people', verbose_name='Empleado')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employeepositions', verbose_name='Posición')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employeeturn', verbose_name='Turno')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=512, null=True)),
                ('date', models.DateField(default=datetime.date(2023, 4, 5), verbose_name='Fecha')),
                ('attendance', models.CharField(max_length=10, verbose_name='Asistencia')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee', verbose_name='Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.banks'),
        ),
    ]
