# Generated by Django 4.1.7 on 2023-05-08 21:16

import core.erp.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=core.erp.models.generar_numero_cuenta, max_length=64, verbose_name='Numeros de cuenta')),
                ('type', models.CharField(max_length=32, verbose_name='Tipo de cuenta')),
                ('bank', models.CharField(choices=[('banR', 'Banreservas'), ('banP', 'Banco Popular'), ('BLeon', 'BHD León'), ('Sbk', 'Scotiabank')], default='banR', max_length=32, verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=64, unique=True)),
                ('firstname', models.CharField(max_length=64, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=64, verbose_name='Apellido')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Femenino')], default='male', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='Direcciones')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('description', models.CharField(max_length=86, verbose_name='Descripcion')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Monto')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Descripcion')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.departments', verbose_name='Departamentos')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('start_turn', models.TimeField(default=datetime.time(0, 0), verbose_name='Inicio del turno')),
                ('end_turn', models.TimeField(default=datetime.time(0, 0), verbose_name='Fin del turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Vacants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Mínimo salario')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Máximo salario')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employeepositions', verbose_name='Posiciones')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.candidatos', verbose_name='Candidatos')),
                ('vacants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.vacants', verbose_name='Vacantes')),
            ],
            options={
                'verbose_name': 'Seleccion',
                'verbose_name_plural': 'Selecciones',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salario')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='Direcciones')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.accountsbank', verbose_name='Cuenta de banco')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.departments', verbose_name='Departamento')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.candidatos', verbose_name='Empleado')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employeepositions', verbose_name='Posición')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employeeturn', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=512, null=True, verbose_name='Observacion')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('attendance', models.BooleanField(default=True, verbose_name='Asistencia')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
