# Generated by Django 4.1.7 on 2023-05-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsbank',
            name='bank',
            field=models.CharField(choices=[('Banreservas', 'Banreservas'), ('Banco Popular', 'Banco Popular'), ('BHD León', 'BHD León'), ('Scotiabank', 'Scotiabank')], default='Banreservas', max_length=32, verbose_name='Banco'),
        ),
    ]
