# Generated by Django 4.1.7 on 2023-06-21 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hiring_date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now, verbose_name='Fecha de contratación'),
        ),
    ]
