# Generated by Django 4.1.7 on 2023-04-06 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeturn',
            name='end_turn',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 21, 58, 43, 963231), verbose_name='Incio del turno'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='start_turn',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 21, 58, 43, 963231), verbose_name='Incio del turno'),
        ),
    ]
