# Generated by Django 4.1.7 on 2023-04-06 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_employeeturn_end_turn_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='AccountsBank',
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='end_turn',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 22, 4, 11, 631485), verbose_name='Incio del turno'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='start_turn',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 22, 4, 11, 631485), verbose_name='Incio del turno'),
        ),
    ]
