# Generated by Django 4.1.7 on 2023-07-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_assistance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=302, unique=True),
        ),
        migrations.AlterField(
            model_name='employeepositions',
            name='name',
            field=models.CharField(max_length=144, verbose_name='Nombre'),
        ),
    ]
