# Generated by Django 4.1.7 on 2023-05-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_accountsbank_bank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuentos',
            options={'verbose_name': 'Descuento', 'verbose_name_plural': 'Descuentos'},
        ),
        migrations.AddField(
            model_name='employee',
            name='codigo',
            field=models.CharField(default='MEU343', max_length=64, verbose_name='Codigo Empleado'),
        ),
    ]
