# Generated by Django 4.1.7 on 2023-05-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_descuentos_options_employee_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='estado',
            field=models.CharField(blank=True, choices=[('hired', 'Contratado'), ('dismissed', 'despedido')], max_length=64, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='codigo',
            field=models.CharField(default='AYZZKX975', max_length=64, verbose_name='Codigo Empleado'),
        ),
    ]
