# Generated by Django 4.1.7 on 2023-06-21 00:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_assistance_assistancedetail_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Referencia')),
                ('type', models.CharField(choices=[('remuneracion', 'REMUNERACION'), ('descuentos', 'DESCUENTOS')], default='Remuneraciones', max_length=15, verbose_name='Tipo')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('order', models.IntegerField(default=0, verbose_name='Posición')),
                ('has_quantity', models.BooleanField(default=False, verbose_name='¿Posee cantidad?')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(choices=[('', '-----------'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=0, verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(default=0.0)),
                ('expenses', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Salario Detalle',
                'verbose_name_plural': 'Salario Detalles',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalaryHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('valor', models.FloatField(default=0.0)),
                ('headings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.headings')),
                ('salary_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.salarydetail')),
            ],
            options={
                'verbose_name': 'Detalle de Salario',
                'verbose_name_plural': 'Detalle de Salarios',
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='Descuentos',
        ),
        migrations.AddField(
            model_name='employee',
            name='hiring_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de contratación'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.salary'),
        ),
    ]
