# Generated by Django 4.1.7 on 2023-04-06 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_attendance_options_alter_departments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='end_turn',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 22, 53, 55, 126587), verbose_name='Incio del turno'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='start_turn',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 22, 53, 55, 126587), verbose_name='Incio del turno'),
        ),
    ]
