# Generated by Django 4.1.7 on 2023-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_departments_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Razón Social')),
                ('rnc', models.CharField(max_length=9, verbose_name='RNC')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('mobile', models.CharField(max_length=15, verbose_name='Teléfono celular')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono convencional')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/%Y/%m/%d', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'permissions': (('view_company', 'Can view company'),),
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='estado',
            field=models.CharField(blank=True, choices=[('Contratado', 'Contratado'), ('Despedido', 'Despedido'), ('Licencia', 'Licencia')], max_length=64, null=True, verbose_name='Estado'),
        ),
    ]
