# Generated by Django 4.1.7 on 2023-08-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_company_alter_employee_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancedetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='salaryheadings',
            name='headings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.headings'),
        ),
    ]
