# Generated by Django 4.1.7 on 2023-04-06 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_departments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsbank',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='banks',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='employeepositions',
            options={'verbose_name': 'Posición', 'verbose_name_plural': 'Posiciones'},
        ),
        migrations.AlterModelOptions(
            name='employeeturn',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='vacants',
            options={'verbose_name': 'Vacante', 'verbose_name_plural': 'Vacantes'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.BooleanField(default=True, verbose_name='Asistencia'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='end_turn',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 22, 59, 52, 858292), verbose_name='Incio del turno'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='start_turn',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 22, 59, 52, 858292), verbose_name='Incio del turno'),
        ),
    ]
