# Generated by Django 4.1.7 on 2023-05-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_employee_address_alter_employee_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='estado',
            field=models.CharField(blank=True, choices=[('Contratado', 'Contratado'), ('Despedido', 'Despedido')], max_length=64, null=True, verbose_name='Estado'),
        ),
    ]
