# Generated by Django 4.1.7 on 2023-04-06 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_accountsbank_options_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 4, 25, 39, 446001, tzinfo=datetime.timezone.utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='end_turn',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 0, 25, 39, 445001), verbose_name='Incio del turno'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='start_turn',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 0, 25, 39, 445001), verbose_name='Incio del turno'),
        ),
        migrations.AlterField(
            model_name='people',
            name='birthdate',
            field=models.DateField(default=datetime.date(2023, 4, 6), verbose_name='Fecha de nacimiento'),
        ),
    ]
