# Generated by Django 4.1.7 on 2023-08-31 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_assistancedetail_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.candidatos', verbose_name='Empleado'),
        ),
    ]
