# Generated by Django 4.1.7 on 2023-10-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_employee_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='cedula',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
