# Generated by Django 4.1.7 on 2023-10-13 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_candidatos_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio de vacaciones')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de termino de vacaciones')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de vacaciones')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones extras')),
                ('state_vacations', models.CharField(choices=[('Accepted', 'Acceptada'), ('Processing', 'Pendiente'), ('Denied', 'Denegada')], max_length=25, verbose_name='Estado de vacaciones')),
                ('empledo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee', verbose_name='Empleado solicitar')),
            ],
            options={
                'verbose_name': 'Vacacion',
                'verbose_name_plural': 'Vacations',
            },
        ),
    ]
