# Generated by Django 4.1.7 on 2023-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_vacations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacations',
            old_name='empledo',
            new_name='empleado',
        ),
        migrations.AlterField(
            model_name='employee',
            name='estado',
            field=models.CharField(blank=True, choices=[('Contratado', 'Contratado'), ('Despedido', 'Despedido'), ('Licencia', 'Licencia'), ('Vacaciones', 'Vacaciones')], max_length=64, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='state_vacations',
            field=models.CharField(choices=[('Acceptada', 'Accepted'), ('Pendiente', 'Processing'), ('Denegada', 'Denied'), ('Finalizada', 'Finished')], max_length=25, verbose_name='Estado de vacaciones'),
        ),
    ]
