# Generated by Django 4.1.7 on 2023-10-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_rename_empledo_vacations_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Recordatorio enviado?'),
        ),
    ]
