# Generated by Django 4.1.7 on 2023-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_people_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
