# Generated by Django 4.1.7 on 2023-05-04 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_alter_departments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepositions',
            name='departament',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp.departments'),
            preserve_default=False,
        ),
    ]
