# Generated by Django 4.2.7 on 2023-11-18 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_alter_candidatos_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.candidatos', unique=True, verbose_name='Empleado'),
        ),
    ]
