# Generated by Django 4.1.7 on 2023-05-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_employeepositions_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepositions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='employeepositions',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nombre'),
        ),
    ]
