# Generated by Django 4.1.7 on 2023-05-04 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_employeepositions_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeturn',
            name='end_turn',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fin del turno'),
        ),
    ]
