# Generated by Django 4.1.7 on 2023-05-04 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_alter_employeeturn_end_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeturn',
            name='end_turn',
            field=models.DateField(default=datetime.date(2023, 5, 4), verbose_name='Fin del turno'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='start_turn',
            field=models.DateField(default=datetime.date(2023, 5, 4), verbose_name='Incio del turno'),
        ),
    ]
