# Generated by Django 4.1.7 on 2023-05-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_alter_employeeturn_end_turn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeturn',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nombre'),
        ),
    ]
