# Generated by Django 4.1.7 on 2023-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_alter_employeeturn_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='observation',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='end_turn',
            field=models.DateTimeField(verbose_name='Fin del turno'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='start_turn',
            field=models.DateTimeField(verbose_name='Inicio del turno'),
        ),
    ]
