# Generated by Django 4.1.7 on 2023-05-05 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_alter_employeeturn_end_turn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=64, unique=True)),
                ('firstname', models.CharField(max_length=64, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=64, verbose_name='Apellido')),
                ('birthdate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[(1, 'Masculino'), (2, 'Femenino')], default='Masculino', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='Direcciones')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.RemoveField(
            model_name='people',
            name='address',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Direcciones'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.candidatos', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='vacants',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.candidatos', verbose_name='Candidatos'),
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
