# Generated by Django 4.1.7 on 2023-05-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_candidatos_remove_people_address_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='gender',
            field=models.CharField(choices=[(1, 'Masculino'), (2, 'Femenino')], max_length=10),
        ),
    ]
