# Generated by Django 4.1.7 on 2023-05-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_alter_candidatos_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='birthdate',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='gender',
            field=models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Femenino')], default='male', max_length=10),
        ),
    ]
