# Generated by Django 4.1.7 on 2023-05-06 04:34
from core.erp.models import generar_numero_cuenta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_alter_candidatos_birthdate_alter_candidatos_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsbank',
            name='number',
            field=models.CharField(default=generar_numero_cuenta, max_length=64),
        ),
    ]
