# Generated by Django 4.1.7 on 2023-05-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_alter_accountsbank_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Seleccion',
                'verbose_name_plural': 'Selecciones',
            },
        ),
        migrations.RemoveField(
            model_name='vacants',
            name='person',
        ),
    ]
