# Generated by Django 4.1.7 on 2023-05-06 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_selection_remove_vacants_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='person',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp.candidatos', verbose_name='Candidatos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='vacants',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='erp.vacants', verbose_name='Vacantes'),
            preserve_default=False,
        ),
    ]
